Repository Team-mozi/Mozi_Backend, pull requests merged in 2025-09, with the labels that each got.

#2 chore: 프로젝트 초기 환경 세팅
  .gitignore
  build.gradle
  src/main/java/com/mozi/global/config/SwaggerConfig.java
  src/main/java/com/mozi/global/config/security/SecurityConfig.java
  src/main/resources/application-template.properties
Labels: 🔧 chore

#8 feature: 이모지 엔티티 및 스웨거 작성
  src/main/java/com/mozi/domain/emoji/controller/EmojiController.java
  src/main/java/com/mozi/domain/emoji/controller/EmojiSpecification.java
  src/main/java/com/mozi/domain/emoji/controller/UserEmojiController.java
  src/main/java/com/mozi/domain/emoji/controller/UserEmojiSpecification.java
  src/main/java/com/mozi/domain/emoji/controller/dto/request/UserEmojiCreateRequest.java
  src/main/java/com/mozi/domain/emoji/controller/dto/response/EmojiResponse.java
  src/main/java/com/mozi/domain/emoji/controller/dto/response/RandomUserEmojiResponse.java
  src/main/java/com/mozi/domain/emoji/controller/dto/response/RepresentativeEmojiResponse.java
  src/main/java/com/mozi/domain/emoji/controller/dto/response/UserEmojiDetailResponse.java
  src/main/java/com/mozi/domain/emoji/controller/dto/response/UserEmojiResponse.java
  src/main/java/com/mozi/domain/emoji/entity/Emoji.java
  src/main/java/com/mozi/domain/emoji/entity/Image.java
  src/main/java/com/mozi/domain/emoji/entity/UserEmoji.java
  src/main/java/com/mozi/global/response/ApiResponse.java
Labels: ✨ feature

#12 chore: 배포 환경 구축 및 CI/CD 설정
  .github/workflows/deploy.yml
  Dockerfile
  build.gradle
  src/main/java/com/mozi/domain/emoji/entity/Image.java
  src/test/java/com/mozi/MoziApplicationTests.java
Labels: 🔧 chore

#20 feature: 회원가입 기능 구현 - jwt
  src/main/java/com/mozi/MoziApplication.java
  src/main/java/com/mozi/domain/user/controller/UserController.java
  src/main/java/com/mozi/domain/user/controller/UserSpecification.java
  src/main/java/com/mozi/domain/user/controller/dto/request/RegisterRequest.java
  src/main/java/com/mozi/domain/user/controller/dto/response/RegisterResponse.java
  src/main/java/com/mozi/domain/user/entity/User.java
  src/main/java/com/mozi/domain/user/repository/UserRepository.java
  src/main/java/com/mozi/domain/user/service/UserService.java
  src/main/java/com/mozi/global/config/security/SecurityConfig.java
  src/main/java/com/mozi/global/exception/BusinessException.java
  src/main/java/com/mozi/global/exception/GlobalExceptionHandler.java
  src/main/java/com/mozi/global/response/ApiResponse.java
Labels: ✨ feature

#28 refactor: db 재조회없이 인증 객체에 id도 담도록 재구조화
  src/main/java/com/mozi/domain/user/controller/dto/request/LoginRequest.java
  src/main/java/com/mozi/domain/user/service/CustomUserDetailsService.java
  src/main/java/com/mozi/global/config/security/CustomUserDetails.java
  src/main/java/com/mozi/global/config/security/SecurityConfig.java
  src/main/java/com/mozi/global/filter/JwtAuthenticationFilter.java
Labels: ♻️ refactor

#32 chore: 스웨거 설정 변경
  src/main/java/com/mozi/domain/user/controller/UserSpecification.java
  src/main/java/com/mozi/global/config/SwaggerConfig.java
  src/main/java/com/mozi/global/config/security/SecurityConfig.java
  src/main/java/com/mozi/global/config/swagger/ApiErrorCodeExamples.java
  src/main/java/com/mozi/global/config/swagger/ExampleHolder.java
  src/main/java/com/mozi/global/config/swagger/SwaggerConfig.java
  src/main/java/com/mozi/global/response/ApiResponse.java
  src/main/resources/application-template.properties
Labels: 🔧 chore

#33 refactor: 스웨거 권한 허용 api 적용
  src/main/java/com/mozi/global/config/swagger/SwaggerConfig.java
Labels: ♻️ refactor
